micronaut:
  application:
    name: micronautLabb2
netty:
  default:
    allocator:

mongodb:
  uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017
  #uri: mongodb://user:password@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/test
db:
  name: 'test'
  collection: 'employee'

